export const items = [
    {
        id: 1,
        title: "Sukienka plus size 42-50",
        price: 85,
        username: "Patrycja",
        description: "Przepiękna sukienka zakupiona w tym miesiącu w sklepie butik na plus. Niestety okazała się zbyt obszerna, a paragon gdzieś zaginął. Zakupiona za ok. 160 zł. Z aktualnej kolekcji, z tego względu też cena sukienki nie podlega negocjacji. Piękna, letnia, w delikatny wzór kwiatów. Można nosić ją z paskiem lub bez.Biust 118-130 Biodra 128-130 Długość 130 Biceps 38",
        size: "XL",
        featured: true,
        free_shipping: true,
        main_image: "img/image-1_main.jpg",
        image2: "img/image-1_2.jpg",
        image3: "img/image-1_3.jpg"
    },
    {
        id: 2,
        title: "Sukienka Tatuum S 36 piękne kolory",
        price: 36,
        username: "Lidka",
        description: "Sprzedam piekna sukienke, jest przewiewna z naturalnego materialu o pieknych kolorach. Dlugosc za kolana przy 170 cm wzrostu, fajny dekolt. Stan oceniam na b. dobry.",
        size: "S",
        featured: true,
        free_shipping: true,
        main_image: "img/image-2.jpg",
        image2: null,
        image3: null
    },
    {
        id: 3,
        title: "Sweter męski 100% wełny merynosa xxl",
        price: 30,
        username: "Joanna",
        size: "XXL",
        description: "Mam do sprzedania sweter z 100% welny merynosa. Rozmiar xxl. Wysylka: 10 zl",
        featured: true,
        free_shipping: false,
        main_image: "img/image-3.jpg",
        image2: null,
        image3: null
    },
    {
        id: 4,
        title: "Kurtka termiczna damska stormberg L softshell przeciwdeszczowa 4f",
        price: 65,
        username: "Robert",
        description: "Kurtka damska rozmiar L.Firmy Stromberg. Oddychajaca ,wodoszczelna,Wiatroszczelna ,\n" +
            "Caloroczna . Możliwa wysyłka 15 zł lub odbior osobisty",
        size: "L",
        featured: false,
        free_shipping: false,
        main_image: "img/image-4.jpg",
        image2: null,
        image3: null
    },
    {
        id: 5,
        title: "Ciemnorozowa bluzka new look 44 luzna z przodu zakladana",
        price: 20,
        username: "Patrycja",
        description: "Bluzke ciezko zmierzyc ,bo na plasko kiepsko sie uklada. Jest na tyle elastyczna ze bedzie rowniez dobra na xxxl.",
        size: "XXL",
        featured: false,
        free_shipping: false,
        main_image: "img/image-5.jpg",
        image2: null,
        image3: null
    },
    {
        id: 6,
        title: "Jeansowa katana cubus dziewczeca 158/164 kozuszek",
        price: 40,
        username: "Patrycja",
        description: "Dlugosc 53,pachy45,biust45,pas44 od pachy33 ,dl.rekawa 60/43 ,sz.rekawa 10 . 100% bawelna material jeansowy, kozuszek100% poliester. Rozmiar dzieciecy jednak nosila osoba w rozmiarze xxs/xs byla idealna. Prosze sugerowac sie wymiarami.",
        size: "XS",
        featured: false,
        free_shipping: false,
        main_image: "img/image-6.jpg",
        image2: null,
        image3: null
    },
]